services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=${USER_POSTGRES}
      - POSTGRESQL_PASSWORD=${PASSWORD_POSTGRES}
      - POSTGRESQL_DATABASE=${NAME_POSTGRES}
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgrs:/var/lib/postgresql/data
    networks:
      - app-network

  aplication:
    build: ./
    depends_on:
     - db
    networks:
      - app-network
    ports:
      - 3000:3000

networks:
  app-network:
    driver: bridge
