services:

  db:
    container_name: db-backend-api
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgrs:/var/lib/postgresql/data
    networks:
      - app-network

  aplication:
    container_name: backend-api
    build: ./
    depends_on:
     - db
    networks:
      - app-network
    ports:
      - 3000:${PORT}

networks:
  app-network:
    driver: bridge
